def gv
pipeline {

    agent any
    environment {
        NEW_VERSION = '1.0.0'
    }

    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage("build") {
            steps {
                script {
                    gv.buildApp()
                }
            }
        }

        stage("test") {
            // when {
            //     expression {
            //         BRANCH_NAME == 'master'
            //     }
            // }
            steps {
                gv.testApp()
            }
        }

        // stage("deploy") {
        //     steps {
                
        //     }
        // }
    }

    post { // executes after all the stages are done

    }
}